import * as fs from 'fs';
import * as path from 'path';

const outlineDir = path.join(process.cwd(), 'node_modules/@tabler/icons/icons/outline');
const outputFile = path.join(process.cwd(), 'lib/icon-data.ts');

// Ensure output directory exists
const outputDir = path.dirname(outputFile);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const files = fs.readdirSync(outlineDir).filter(f => f.endsWith('.svg'));

const iconData: Record<string, string> = {};

for (const file of files) {
  const name = path.basename(file, '.svg');
  const content = fs.readFileSync(path.join(outlineDir, file), 'utf-8');

  // Extract everything inside the <svg> tag
  const svgMatch = content.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!svgMatch) continue;

  const inner = svgMatch[1]
    .replace(/\s+/g, ' ')
    .trim();

  iconData[name] = inner;
}

const iconNames = Object.keys(iconData).sort();

const lines: string[] = [
  '// AUTO-GENERATED by scripts/extract-icons.ts — do not edit manually',
  '',
  `export const iconData: Record<string, string> = {`,
];

for (const name of iconNames) {
  const escaped = iconData[name].replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');
  lines.push(`  ${JSON.stringify(name)}: \`${escaped}\`,`);
}

lines.push('};');
lines.push('');
lines.push('export const iconNames: string[] = Object.keys(iconData).sort();');
lines.push('');

fs.writeFileSync(outputFile, lines.join('\n'), 'utf-8');
console.log(`Extracted ${iconNames.length} icons to ${outputFile}`);
